export const mockReports = [
  {
    id: "FIR-001",
    title: "Suspicious Activity at Lajpat Nagar Market",
    type: "Suspicious Activity",
    description:
      "Witness reported two individuals attempting to force entry into a jewelry shop in Lajpat Nagar. Suspects fled on motorcycle when spotted by shopkeeper.",
    timestamp: "2023-06-15T21:30:00",
    location: {
      address: "123 Lajpat Nagar Market, Delhi",
      coordinates: { lat: 28.5709, lng: 77.2432 },
    },
    reportedBy: "Sunita Sharma",
    contactInfo: {
      phone: "9855123456",
      email: "sunita.sharma@gmail.com",
    },
    status: "In Progress",
    priority: "Medium",
    verified: true,
    idVerified: true,
    assignedOfficer: "Sub-Inspector Verma",
  },
  {
    id: "FIR-002",
    title: "Two-wheeler Theft at Cubbon Park",
    type: "Theft",
    description:
      "Honda Activa scooter stolen from parking area near Cubbon Park. Incident occurred between 2-4 PM. Vehicle number KA-01-AB-1234.",
    timestamp: "2023-06-14T16:45:00",
    location: {
      address: "Cubbon Park, East Gate, Bengaluru",
      coordinates: { lat: 12.9767, lng: 77.5923 },
    },
    reportedBy: "Mahesh Kumar",
    contactInfo: {
      phone: "8877654321",
      email: "mahesh.k@hotmail.com",
    },
    status: "Resolved",
    priority: "Low",
    verified: true,
    idVerified: true,
    assignedOfficer: "Constable Subramaniam",
  },
  {
    id: "FIR-003",
    title: "Residential Burglary in Banjara Hills",
    type: "Burglary",
    description:
      "Home broken into while residents were away for wedding. Gold jewelry and electronics reported missing. Entry through rear window. Servant quarters lock also broken.",
    timestamp: "2023-06-13T08:15:00",
    location: {
      address: "456 Road No. 12, Banjara Hills, Hyderabad",
      coordinates: { lat: 17.4156, lng: 78.4347 },
    },
    reportedBy: "Rajesh Kapoor",
    contactInfo: {
      phone: "7766123456",
      email: "rajesh.kapoor@outlook.com",
    },
    status: "In Progress",
    priority: "High",
    verified: true,
    idVerified: true,
    assignedOfficer: "Inspector Reddy",
  },
  {
    id: "FIR-004",
    title: "Vandalism at Municipal Corporation Building",
    type: "Vandalism",
    description:
      "Graffiti found on the east wall of the Municipal Corporation building. CCTV footage shows three young men at 2 AM.",
    timestamp: "2023-06-12T17:20:00",
    location: {
      address: "789 MG Road, Pune",
      coordinates: { lat: 18.5195, lng: 73.8553 },
    },
    reportedBy: "Municipal Corporation Staff",
    contactInfo: {
      phone: "9988123456",
      email: "admin@punemc.gov.in",
    },
    status: "Pending",
    priority: "Low",
    verified: false,
    idVerified: true,
    assignedOfficer: null,
  },
  {
    id: "FIR-005",
    title: "Noise Complaint at Andheri Housing Society",
    type: "Disturbance",
    description:
      "Ongoing loud music and shouting from flat 3B. Multiple complaints from society members over the past week due to late night parties.",
    timestamp: "2023-06-11T23:10:00",
    location: {
      address: "Shanti Niketan Society, Flat 3B, Andheri East, Mumbai",
      coordinates: { lat: 19.1136, lng: 72.8697 },
    },
    reportedBy: "Multiple Society Residents",
    contactInfo: {
      phone: "8855123456",
      email: "secretary@shantiniketansociety.com",
    },
    status: "Resolved",
    priority: "Low",
    verified: true,
    idVerified: false,
    assignedOfficer: "Constable Patil",
  },
  {
    id: "FIR-006",
    title: "Traffic Accident on NH-8",
    type: "Accident",
    description:
      "Auto-rickshaw and car collision at the Gurgaon toll plaza. Minor injuries reported. Auto-rickshaw driver taken to government hospital.",
    timestamp: "2023-06-10T15:45:00",
    location: {
      address: "NH-8 Toll Plaza, Gurgaon",
      coordinates: { lat: 28.4595, lng: 77.0266 },
    },
    reportedBy: "Traffic Police Officer",
    contactInfo: {
      phone: "9911123456",
      email: "traffic@gurgaonpolice.gov.in",
    },
    status: "Resolved",
    priority: "Medium",
    verified: true,
    idVerified: true,
    assignedOfficer: "SI Chauhan",
  },
  {
    id: "FIR-007",
    title: "Missing Person Report",
    type: "Emergency",
    description:
      "16-year-old girl not returned home from coaching center. Last seen at Aakash Institute at approximately 3:30 PM wearing salwar kameez and carrying a blue backpack.",
    timestamp: "2023-06-09T20:30:00",
    location: {
      address: "Aakash Institute, Sector 14, Chandigarh",
      coordinates: { lat: 30.7333, lng: 76.7794 },
    },
    reportedBy: "Parents",
    contactInfo: {
      phone: "9944123456",
      email: "sharma.family@gmail.com",
    },
    status: "In Progress",
    priority: "High",
    verified: true,
    idVerified: true,
    assignedOfficer: "Inspector Singh",
  },
  {
    id: "FIR-008",
    title: "Shoplifting at Phoenix Mall",
    type: "Theft",
    description:
      "Suspect caught on security camera concealing merchandise at Lifestyle store in Phoenix Mall. Approximate value of stolen items: ₹15,000.",
    timestamp: "2023-06-08T14:20:00",
    location: {
      address: "Phoenix Mall, Whitefield, Bangalore",
      coordinates: { lat: 12.9968, lng: 77.6968 },
    },
    reportedBy: "Store Manager",
    contactInfo: {
      phone: "8844123456",
      email: "manager@lifestylestore.com",
    },
    status: "Pending",
    priority: "Low",
    verified: false,
    idVerified: true,
    assignedOfficer: null,
  },
  {
    id: "FIR-009",
    title: "Drug Activity in Lodhi Gardens",
    type: "Suspicious Activity",
    description:
      "Multiple reports of drug deals occurring near the north fountain in Lodhi Gardens, primarily after sunset hours.",
    timestamp: "2023-06-07T19:15:00",
    location: {
      address: "Lodhi Gardens, North Fountain Area, New Delhi",
      coordinates: { lat: 28.5931, lng: 77.2215 },
    },
    reportedBy: "Anonymous Tip",
    contactInfo: {
      phone: null,
      email: null,
    },
    status: "In Progress",
    priority: "Medium",
    verified: true,
    idVerified: false,
    assignedOfficer: "Constable Kumar",
  },
  {
    id: "FIR-010",
    title: "Armed Robbery at Petrol Pump",
    type: "Emergency",
    description:
      "Two masked individuals on motorcycle with country-made pistol demanded cash from petrol pump. Approximately ₹25,000 taken. Suspects fled towards Ring Road.",
    timestamp: "2023-06-06T22:05:00",
    location: {
      address: "Indian Oil Petrol Pump, Dwarka Sector 12, Delhi",
      coordinates: { lat: 28.5921, lng: 77.0460 },
    },
    reportedBy: "Petrol Pump Attendant",
    contactInfo: {
      phone: "9900123456",
      email: "employee@indianoil.com",
    },
    status: "In Progress",
    priority: "High",
    verified: true,
    idVerified: true,
    assignedOfficer: "Inspector Sharma",
  },
  {
    id: "FIR-011",
    title: "Lost Child at Saket Mall",
    type: "Emergency",
    description:
      "5-year-old boy separated from parents at Select Citywalk Mall. Wearing blue kurta and jeans.",
    timestamp: "2023-06-05T16:30:00",
    location: {
      address: "Select Citywalk Mall, Saket, Delhi",
      coordinates: { lat: 28.5292, lng: 77.2195 },
    },
    reportedBy: "Mall Security Guard",
    contactInfo: {
      phone: "8811123456",
      email: "security@selectcitywalk.com",
    },
    status: "Resolved",
    priority: "High",
    verified: true,
    idVerified: true,
    assignedOfficer: "SI Kaur",
  },
  {
    id: "FIR-012",
    title: "Illegal Dumping Behind Restaurant",
    type: "Environmental",
    description:
      "Multiple instances of commercial waste being dumped in the alley behind Taste of Punjab restaurant. Creating sanitation hazard in residential area.",
    timestamp: "2023-06-04T11:45:00",
    location: {
      address: "Lane behind Taste of Punjab, Connaught Place, Delhi",
      coordinates: { lat: 28.6315, lng: 77.2167 },
    },
    reportedBy: "Neighboring Resident",
    contactInfo: {
      phone: "7722123456",
      email: "resident@gmail.com",
    },
    status: "Pending",
    priority: "Medium",
    verified: false,
    idVerified: true,
    assignedOfficer: null,
  },
  {
    id: "FIR-013",
    title: "Domestic Disturbance in Malad",
    type: "Disturbance",
    description:
      "Neighbors reported shouting and sounds of items breaking from flat 5C. History of similar calls to this address.",
    timestamp: "2023-06-03T21:50:00",
    location: {
      address: "Sai Palace Society, Flat 5C, Malad West, Mumbai",
      coordinates: { lat: 19.1762, lng: 72.8400 },
    },
    reportedBy: "Society Watchman",
    contactInfo: {
      phone: "9933123456",
      email: "watchman@saipalace.com",
    },
    status: "Resolved",
    priority: "High",
    verified: true,
    idVerified: false,
    assignedOfficer: "Constable Joshi",
  },
  {
    id: "FIR-014",
    title: "Bicycle Theft at Railway Station",
    type: "Theft",
    description:
      "Locked bicycle stolen from the bike stand at Dadar Railway Station between 8 AM and 6 PM. Hero cycle with child seat.",
    timestamp: "2023-06-02T18:20:00",
    location: {
      address: "Dadar Railway Station, West Side, Mumbai",
      coordinates: { lat: 19.0178, lng: 72.8478 },
    },
    reportedBy: "Bicycle Owner",
    contactInfo: {
      phone: "8822123456",
      email: "cyclist@yahoo.com",
    },
    status: "Pending",
    priority: "Low",
    verified: true,
    idVerified: true,
    assignedOfficer: null,
  },
  {
    id: "FIR-015",
    title: "Suspicious Package at ISBT",
    type: "Emergency",
    description: "Unattended bag left on bench at Platform 5. No owner in vicinity for over 30 minutes.",
    timestamp: "2023-06-01T12:10:00",
    location: {
      address: "ISBT Kashmere Gate, Platform 5, Delhi",
      coordinates: { lat: 28.6675, lng: 77.2321 },
    },
    reportedBy: "Bus Terminal Security",
    contactInfo: {
      phone: "9966123456",
      email: "security@isbt.delhi.gov.in",
    },
    status: "Resolved",
    priority: "High",
    verified: true,
    idVerified: true,
    assignedOfficer: "Bomb Disposal Squad",
  },
]

export const mockSosCalls = [
  {
    id: "PCR-001",
    location: "MAROL, ANDHERI EAST, MUMBAI",
    timestamp: "2023-06-15T10:30:00",
    status: "Active",
    priority: "High",
    receivedBy: "HC Deshmukh",
    respondingOfficer: null,
    callerName: "Amit Patel",
    callerPhone: "9855123456",
    description: "Reported break-in in progress at residential address. Caller hiding in bathroom.",
    notes: "Caller whispered, sounds distressed. Mentioned two intruders. Mobilizing nearest PCR van.",
  },
  {
    id: "PCR-002",
    location: "PHOENIX MARKETCITY, KURLA, MUMBAI",
    timestamp: "2023-06-15T09:45:00",
    status: "Responding",
    priority: "High",
    receivedBy: "HC Sawant",
    respondingOfficer: "SI Jadhav",
    callerName: "Meena Iyer",
    callerPhone: "8877654321",
    description: "Medical emergency, elderly person collapsed near food court. Possible heart attack.",
    notes: "108 Ambulance also dispatched. ETA 5 minutes. Mall security providing first aid.",
  },
  {
    id: "PCR-003",
    location: "MAHIM RAILWAY STATION, MUMBAI",
    timestamp: "2023-06-15T08:15:00",
    status: "Responding",
    priority: "Medium",
    receivedBy: "HC Sawant",
    respondingOfficer: "Constable Shinde",
    callerName: "Railway Police Force",
    callerPhone: "9988123456",
    description: "Suspicious package left unattended on platform 3. Rush hour crowd present.",
    notes: "CCTV footage being reviewed. Railway Police coordinating passenger evacuation.",
  },
  {
    id: "PCR-004",
    location: "LALBAUG, LOWER PAREL, MUMBAI",
    timestamp: "2023-06-14T22:30:00",
    status: "Resolved",
    priority: "High",
    receivedBy: "HC Deshmukh",
    respondingOfficer: "SI Tiwari",
    callerName: "Anonymous",
    callerPhone: "Unknown",
    description: "Domestic disturbance reported in Chawl building. Loud shouting and possible violence.",
    notes: "Third call from this address this month. Women helpline notified.",
  },
  {
    id: "PCR-005",
    location: "LINKING ROAD, BANDRA WEST, MUMBAI",
    timestamp: "2023-06-14T20:15:00",
    status: "Resolved",
    priority: "Medium",
    receivedBy: "HC Sawant",
    respondingOfficer: "Constable Sharma",
    callerName: "Hotel Manager",
    callerPhone: "7766123456",
    description: "Intoxicated customer refusing to leave hotel restaurant and threatening staff.",
    notes: "Subject removed peacefully, no FIR filed. Friend took responsibility.",
  },
  {
    id: "PCR-006",
    location: "DADAR EAST, MUMBAI",
    timestamp: "2023-06-14T16:45:00",
    status: "Active",
    priority: "High",
    receivedBy: "HC Deshmukh",
    respondingOfficer: null,
    callerName: "School Principal",
    callerPhone: "9944123456",
    description: "Unauthorized person on school grounds, possibly carrying weapon in backpack.",
    notes: "School in lockdown. Multiple PCR vans dispatched. Anti-Terror Squad alerted.",
  },
  {
    id: "PCR-007",
    location: "CHEMBUR, MUMBAI",
    timestamp: "2023-06-14T14:20:00",
    status: "Responding",
    priority: "Low",
    receivedBy: "HC Sawant",
    respondingOfficer: "Constable Yadav",
    callerName: "Petrol Pump Attendant",
    callerPhone: "8844123456",
    description: "Bike rider drove off without paying for fuel. ₹500 worth petrol.",
    notes: "Registration number and bike description provided. MH-02-AB-1234, red Pulsar.",
  },
  {
    id: "PCR-008",
    location: "WORLI, MUMBAI",
    timestamp: "2023-06-14T11:10:00",
    status: "Resolved",
    priority: "Medium",
    receivedBy: "HC Deshmukh",
    respondingOfficer: "SI Kulkarni",
    callerName: "Bank Manager",
    callerPhone: "9900123456",
    description: "Silent alarm triggered at SBI branch during routine operation.",
    notes: "False alarm confirmed. System malfunction due to power fluctuation.",
  },
]

